name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 

    - name: up dir
      run: cd ..
    - name: check dir
      run: dir .  
    - name: up dir
      run: cd ..
    - name: check dir
      run: dir . 
