name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Create build directory
      run: cmake -S . -B ../tree_build
    - name: Build
      run: cmake --build ../tree_build
    - name: Test
      run: ctest --test-dir ../tree_build
