name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Create build directory
      run: cmake -S . -B ../tree_build
    - name: test
      run: |
        dir .
        cd tree_build
        dir .
        ctest
