name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: cmake/setup-cmake@v2
      with:
        cmake-version: '3.21.2'  # Adjust version as needed

    - name: Create build directory
      run: cmake -S . -B ../tree_build
